Fix multiplying polynomials, addition bug, simplify / optimize code
Multiplying:

```
a = Polynomial(1, 2, 3) * Polynomial(1, 2, 3)
>>> Traceback (most recent call last):
>>> [...]
>>> AttributeError: 'Polynomial' object has no attribute 'get_monomials'
```

Adding

```
a = Polynomial(1, 2, 3)
p = a + 0
p.a = 5
print(a.a)
>>> 5
```

I made some fixes in other places and optimized other parts of the code - using less reversed() statements and so forth.
I also implemented slices, so it is now possible to get a portion of the coefficients from a Polynomial (eg. do Polynomial(1, 2, 3)[0:2] to get 3, 2.)